name: eql_cmx_portal_cicd_transport_portal_data_pipeline_to_build_env.yml

on:
  workflow_call :
    inputs:
      portal_name:
        description: 'name of the portal'
        required: true
        type: string
    secrets:
      dev_url:
        description: 'portal_data environment url.'
        required: true      
      dev_client_id:
        description: 'The portal_data client id'
        required: true
      dev_secrets_id:
        description: 'The secret value for authentication for portal_data'
        required: true
      dev_tenant_id:
        description: 'The tenant id'
        required: true
      build_url:
        description: 'portal_data environment url.'
        required: true      
      build_client_id:
        description: 'The portal_data client id'
        required: true
      build_secrets_id:
        description: 'The secret value for authentication for portal_data'
        required: true
      build_tenant_id: 
        description: 'The tenant id'
        required: true
      website_id:
        description: 'The website id'
        required: true
        

jobs:
  download-portal-data-from-dev-env:
    runs-on:  ubuntu-latest
    environment: dev
    env:
      RUNNER_DEBUG: 1
    steps:

    - uses: actions/checkout@v3
      with:
        lfs: true
        ref: develop
        
    - name: download-paportal
      uses: microsoft/powerplatform-actions/download-paportal@v0
      with:
        environment-url: ${{ secrets.dev_url }}
        app-id: ${{ secrets.dev_client_id }}
        client-secret: ${{ secrets.dev_secrets_id }}
        tenant-id: ${{ secrets.dev_tenant_id }}
        download-path: portaldata
        website-id:  ${{ secrets.website_id }} 
        overwrite: true
        
    - name: push portal data to branch
      run: |
          ls -d */
          git --version
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git status
          git pull origin
          git add portaldata
          git commit -m "Added portaldata to branch"
          git push
      env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Display structure of downloaded files
      run: ls -R
        

  upload-portal-data-to-build-env:
    needs: [ download-portal-data-from-dev-env ]
    runs-on:  ubuntu-latest
    environment: build
    env:
      RUNNER_DEBUG: 1
    steps:

    - uses: actions/checkout@v3
      with:
        lfs: true
        ref: develop
  
    - name: Display List of Directories
      run: |
          ls -d */
      env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}


    - name: upload-paportal
      uses: microsoft/powerplatform-actions/upload-paportal@v0
      with:
        environment-url: ${{ secrets.build_url }}
        app-id: ${{ secrets.build_client_id }}
        client-secret: ${{ secrets.build_secrets_id }}
        tenant-id: ${{ secrets.build_tenant_id }}
        upload-path: portaldata/${{ inputs.portal_name }}
        
